version: 2.1
executors:
  ci-executor:
    docker:
      - image: githubtraining/ci-custom:latest
jobs:
  build:
    executor: ci-executor
    steps:
      - checkout
 custom-build

      - run:
          name: build dependencies
          command: bundle install

      - run:
          name: bundle exec jekyll build
          command: bundle exec jekyll build

      - run:
          name: notify build is finished
          command: echo "The build is finished!"

 master
